name: Deploy to Production

on:
  release:
    types:
      - published

jobs:
  deploy:
    # Do not deploy in the main repository, only in user projects
    if: github.repository_owner != 'fastapi'
    runs-on:
      - self-hosted
      - production
    env:
      ENVIRONMENT: production
      DOMAIN: ${{ vars.DOMAIN_PRODUCTION }}
      STACK_NAME: ${{ vars.STACK_NAME_PRODUCTION }}
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      FRONTEND_HOST: https://dashboard.${{ vars.DOMAIN_PRODUCTION }}
      BACKEND_CORS_ORIGINS: ${{ secrets.BACKEND_CORS_ORIGINS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_PORT: ${{ vars.SMTP_PORT }}
      SMTP_TLS: ${{ vars.SMTP_TLS }}
      SMTP_SSL: ${{ vars.SMTP_SSL }}
      EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL }}
      POSTGRES_SERVER: db
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      DOCKER_IMAGE_BACKEND: ${{ vars.DOCKER_IMAGE_BACKEND }}
      DOCKER_IMAGE_FRONTEND: ${{ vars.DOCKER_IMAGE_FRONTEND }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build containers
        run: docker compose -f docker-compose.yml --project-name "$STACK_NAME" build
      - name: Start containers
        run: docker compose -f docker-compose.yml --project-name "$STACK_NAME" up -d
